---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: scheduler-operator-leader-election-rolebinding
  namespace: ns1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: scheduler-operator-leader-election-role
subjects:
- kind: ServiceAccount
  name: scheduler-operator-sa
  namespace: ns1