# permissions for end users to view metricschedulers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: metricscheduler-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: go
    app.kubernetes.io/part-of: go
    app.kubernetes.io/managed-by: kustomize
  name: metricscheduler-viewer-role
rules:
- apiGroups:
  - scheduler.uclm.es
  resources:
  - metricschedulers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scheduler.uclm.es
  resources:
  - metricschedulers/status
  verbs:
  - get
