
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scheduler-operator.fullname" . }}
  namespace: {{.Release.Namespace}}
  labels:
    control-plane: {{ include "scheduler-operator.fullname" . }}
data:
  # LOG Config
  LOG_DEV_MODE: "{{ .Values.log.devMode }}"
  LOG_ENCODER: "{{ .Values.log.encoder }}"
  LOG_LEVEL_OPERATOR: "{{ .Values.log.levelOperator }}"
  LOG_LEVEL_STRACKTRACE: "{{ .Values.log.levelStacktrace }}"

  # Namespaces to Watch
  WATCH_NAMESPACES: "{{ .Values.watchNamespaces }}"

  # Image Config
  IMG_METRICSCHEDULER: "{{ .Values.image.repository }}/{{ .Values.images.metricScheduler }}:{{ .Values.image.tag }}"
