{{- if .Values.serviceAccount.create }}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ $.Release.Namespace }}
  name: {{ include "scheduler-operator.serviceAccountName" $ }}
{{- end }}