
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "scheduler-operator.fullname" $ }}-webhook-service
  namespace: {{ $.Release.Namespace }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    control-plane: {{ include "scheduler-operator.fullname" $ }}
