apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: ns1
  name: scheduler
  labels:
    app: scheduler
    component: scheduler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scheduler
subjects:
- kind: ServiceAccount
  name: scheduler
  namespace: ns1
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: system:kube-scheduler