---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler-operator
  namespace: ns1
  labels:
    control-plane: scheduler-operator
spec:
  selector:
    matchLabels:
      control-plane: scheduler-operator
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: scheduler-operator
    spec:
      serviceAccountName: scheduler-operator-sa
      hostname: manager
      subdomain: scheduler-operator
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
        runAsGroup: 2000
        fsGroupChangePolicy: "OnRootMismatch"
      containers:
        - image: localhost:5000/albertogomez/scheduler-operator:0.0.0
          imagePullPolicy: Always
          name: manager
          ports:
            - containerPort: 8080
              name: metrics
              protocol: TCP
          envFrom:
            - configMapRef:
                name: scheduler-operator
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          securityContext:
            allowPrivilegeEscalation: false
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
      terminationGracePeriodSeconds: 10
