apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: prometheus-postgres-adapter
  labels:
    app: postgresql-prometheus-adapter
spec:
  selector:
    matchLabels:
      app: postgresql-prometheus-adapter
  replicas: 1
  template:
    metadata:
      labels:
        app: postgresql-prometheus-adapter
    spec:
      hostname: adapter
      subdomain: adapter-example
      containers:
        - name: prometheus-postgres-adapter
          image: localhost:5000/crunchydata/postgresql-prometheus-adapter:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9201
              name: listen
              protocol: TCP
          env:
            - name: DATABASE_URL
              value: "postgres://prometheus:prometheus@postgres:5432/prometheus"
            - name: ADAPTER_SEND_TIMEOUT
              value: "30s"
            - name: WEB_LISTEN_ADDRESS
              value: ":9201"
            - name: WEB_TELEMETRY_PATH
              value: "/metrics"
            - name: LOG_LEVEL
              value: "info"
            - name: LOG_FORMAT
              value: "logfmt"
            - name: PG_PARTITIONS
              value: "hourly"
            - name: PG_COMMIT_SECS
              value: "60"
            - name: PG_COMMIT_ROWS
              value: "5000"
            - name: PG_THREADS
              value: "1"
            - name: PARSER_THREADS
              value: "1"
          resources:
            requests:
              cpu: 1500m
              memory: 3072M
            limits:
              cpu: 1500m
              memory: 3072M
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-prometheus-adapter
  namespace: monitoring
spec:
  selector:
    app: postgresql-prometheus-adapter
  ports:
    - port: 9201
      targetPort: 9201