#apiVersion: kafka.strimzi.io/v1beta2
#kind: Kafka
#metadata:
#  name: kafka-cluster
#  namespace: kafka
#spec:
#  kafka:
#    template:
#      pod:
#        securityContext:
#           runAsUser: 1001
#           runAsGroup: 1001
#           fsGroup: 1001
#    version: 3.4.0
#    replicas: 1
#    listeners:
#      - name: plain
#        port: 9092
#        type: internal
#        tls: false
#      - name: tls
#        port: 9093
#        type: internal
#        tls: true
#    config:
#      offsets.topic.replication.factor: 1
#      transaction.state.log.replication.factor: 1
##      transaction.state.log.min.isr: 1
#      default.replication.factor: 1
##      min.insync.replicas: 1
#      inter.broker.protocol.version: "3.4"
#    storage:
#      type: jbod
#      volumes:
#      - id: 0
#        type: persistent-claim
#        size: 100Gi
#        deleteClaim: false
#  zookeeper:
#    template:
#      pod:
#        securityContext:
#           runAsUser: 1001
#           runAsGroup: 1001
#           fsGroup: 1001
#    replicas: 1
#    storage:
#      type: persistent-claim
#      size: 100Gi
#      deleteClaim: false
#  entityOperator:
#    topicOperator: {}
#    userOperator: {}
apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
spec:
  kafka:
    version: 3.4.0
    replicas: 1
    resources:
      requests:
        memory: 1Gi
        cpu: "1"
      limits:
        memory: 2Gi
        cpu: "2"
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.4"
    storage:
      type: ephemeral
  zookeeper:
    replicas: 1
    resources:
      requests:
        memory: 1Gi
        cpu: "1"
      limits:
        memory: 2Gi
        cpu: "2"
    storage:
      type: ephemeral
  entityOperator:
    topicOperator: {}
    userOperator: {}