apiVersion: v1
kind: Pod
metadata:
  name: tfm-ubuntu
  namespace: ns1
  labels:
    app: tfm-ubuntu
spec:
  containers:
  - name: tfm-ubuntu
    image: ubuntu:latest
    command: ["/bin/sleep", "3650d"]
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
