apiVersion: v1
kind: Pod
metadata:
  name: tfm-ubuntu-constraints
  namespace: ns2
  labels:
    app: tfm-ubuntu-constraints
spec:
  containers:
  - name: tfm-ubuntu-constraints
    image: ubuntu:latest
    command: ["/bin/sleep", "3650d"]
    imagePullPolicy: IfNotPresent
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                  - tfm-dev-worker2
  restartPolicy: Always
